"""In-repo RAGAS evaluator using a local Ollama LLM as judge (default: qwen2.5:7b).

WHY THIS FILE EXISTS
--------------------
After ``run_baseline.py`` produces JSONL files with LLM answers and retrieved
contexts, this script computes objective RAGAS metrics using a separate judge
LLM (default: ``qwen2.5:7b``).  This separates generation from evaluation and
allows re-evaluating the same run with a different judge or new metrics.

JUDGE MODEL CHOICE
------------------
``qwen2.5:7b`` is chosen as the default for two reasons:

  1. **Avoids self-evaluation bias** — answers are generated by ``gemma3:27b``;
     using any gemma model as judge risks the judge favouring its own family's
     phrasing and output style.  Qwen is a different model family.

  2. **context_precision compatibility** — RAGAS ContextPrecision requires the
     judge to output a bare Yes or No per chunk.  The 14b Qwen model appends
     verbose reasoning which breaks the parser (confirmed: context_recall=0.88
     co-existing with context_precision=0.0 — a logical impossibility).
     The 7b variant is more concise and literal about format instructions,
     producing reliably parseable Yes/No responses.

METRICS PER PIPELINE
--------------------
Metrics are chosen based on what each pipeline provides:

  ``rag_only``        → answer_correctness, answer_relevancy, faithfulness,
                        context_precision, context_recall
                        (has retrieved contexts)

  ``hybrid_rag``      → answer_correctness, answer_relevancy, faithfulness,
                        context_precision, context_recall
                        (same retrieved contexts as rag_only)

  ``pretrained_only`` → answer_correctness, answer_relevancy only
                        (no contexts → context metrics not meaningful)

  ``direct_kb``       → answer_correctness, answer_relevancy, faithfulness,
                        context_precision, context_recall
                        (has all 205 KB rows as contexts)

NOTE on context_precision judge calibration:
  context_precision requires the judge to output a clean Yes/No per chunk.
  The default judge (qwen2.5:7b) is chosen to be concise enough to produce
  parseable Yes/No responses.  The larger qwen2.5:14b appends verbose reasoning
  which breaks the parser — confirmed by context_recall=0.88 co-existing with
  context_precision=0.0, a logical impossibility that indicates parse failure,
  not retrieval failure.  If context_precision scores are unexpectedly 0.0,
  try a smaller or more instruction-following judge via --judge-model.

JUDGE LLM SETUP
---------------
Requires official ragas from explodinggradients (``pip install 'ragas>=0.1.9,<0.2.0'``).
Do NOT use the vibrantlabsai fork (ragas 0.4.x): that fork uses the ``instructor``
library to enforce structured JSON output via OpenAI function-calling, which is
incompatible with Ollama — context_precision scores 0 for every chunk regardless
of model size.  Official ragas 0.1.x uses text-based prompting for all metrics
and works correctly with Ollama.

Uses ``ChatOllama`` (chat model), NOT ``OllamaLLM`` (completion model).  Official
ragas sends each metric evaluation as a structured chat message (system + user
roles).  A completion model receives only the flattened raw text and cannot
maintain the role boundaries, causing metrics to silently return 0.  ChatOllama
is the correct LangChain class for ragas + Ollama.

The LLM and embeddings are passed globally to ``evaluate(llm=..., embeddings=...)``,
not to individual metric constructors.  This is the standard pattern for
official ragas 0.1.x.

RAGAS DATASET FORMAT
--------------------
Official ragas 0.1.x standard columns:

  - ``question``      : the user question
  - ``answer``        : the LLM-generated answer
  - ``ground_truth``  : the human-validated answer
  - ``contexts``      : list of retrieved text strings (or ``[""]`` if none)

EVENT LOOP ISOLATION
--------------------
RAGAS 0.4.x closes the asyncio event loop when ``evaluate()`` returns.
Evaluating multiple pipelines sequentially in the same process therefore
fails with ``RuntimeError: Event loop is closed`` on the second pipeline.

The fix: each pipeline is evaluated in its own ``multiprocessing`` subprocess
(``spawn`` context).  Each subprocess gets a fresh Python interpreter with a
new event loop.  Results are returned via a temp JSON file so they survive the
subprocess exit cleanly.

OUTPUT
------
``<run-dir>/ragas_scores.json`` with structure::
    {
      "metadata": { "run_dir": ..., "judge_model": ..., "run_date": ... },
      "by_pipeline": {
        "<pipeline>": {
          "per_question": [ { "question_id": ..., "answer_correctness": ... } ],
          "aggregate":    { "answer_correctness": { "mean": ..., "std": ..., ... } }
        }
      }
    }

TIMEOUT ARCHITECTURE
--------------------
There are TWO independent timeouts that must both be large enough:

  1. LangChain client timeout  (``--judge-timeout``, default 300s)
     Controls how long the HTTP call to Ollama waits per token chunk.
     Passed to ``OllamaLLM(timeout=...)``.

  2. RAGAS RunConfig timeout  (also ``--judge-timeout``, same value)
     Controls how long RAGAS waits for a complete metric evaluation job.
     Passed to ``RunConfig(timeout=...)``.

Both are set from the same ``--judge-timeout`` flag.  ``max_workers=1``
is also set in RunConfig to prevent concurrent Ollama calls which cause
resource contention and increase timeout probability on local hardware.

USAGE
-----
    python -m georgia_ev_intelligence.runtime_pipeline.hybrid_retrieval.evaluate_ragas \\
        --run-dir georgia_ev_intelligence/outputs/baselines/<timestamp> \\
        --judge-model qwen2.5:7b \\
        --judge-timeout 600

    # Use a smaller/faster judge model to avoid timeouts on slower hardware:
    python -m ... --judge-model qwen2.5:7b --judge-timeout 300

Reads the JSONL files produced by ``run_baseline.py`` and computes RAGAS
metrics per pipeline.  Results are written as a JSON file inside the run
directory.

Usage:
    python -m georgia_ev_intelligence.runtime_pipeline.hybrid_retrieval.evaluate_ragas \\
        --run-dir georgia_ev_intelligence/outputs/baselines/<timestamp> \\
        --judge-model qwen2.5:7b

    # Custom embedding model and output path:
    python -m ... \\
        --run-dir ... \\
        --judge-model qwen2.5:7b \\
        --embed-model nomic-embed-text \\
        --output ragas_scores.json

Metrics computed per pipeline:
    rag_only        — answer_correctness, answer_relevancy, faithfulness, context_precision, context_recall
    hybrid_rag      — answer_correctness, answer_relevancy, faithfulness, context_precision, context_recall
    pretrained_only — answer_correctness, answer_relevancy
    direct_kb       — answer_correctness, answer_relevancy, faithfulness, context_precision, context_recall

    context_precision requires a concise Yes/No judge.  qwen2.5:7b (default)
    is chosen for this: same Qwen family as the answer-quality metrics, avoids
    gemma self-evaluation bias, and is concise enough for Yes/No parsing.
"""
from __future__ import annotations

import argparse
import json
import multiprocessing
import statistics
import tempfile
import traceback as _traceback
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Lazy imports for optional RAGAS / LangChain dependencies
# ---------------------------------------------------------------------------

def _import_ragas():
    """Import RAGAS components and return them as a namespace."""
    try:
        from datasets import Dataset
        from ragas import evaluate
        from ragas.llms import LangchainLLMWrapper
        from ragas.embeddings import LangchainEmbeddingsWrapper
        from ragas.metrics import (
            AnswerCorrectness,
            AnswerRelevancy,
            Faithfulness,
            ContextRecall,
            ContextPrecision,
        )
        from ragas.run_config import RunConfig
        return {
            "Dataset": Dataset,
            "evaluate": evaluate,
            "LangchainLLMWrapper": LangchainLLMWrapper,
            "LangchainEmbeddingsWrapper": LangchainEmbeddingsWrapper,
            "AnswerCorrectness": AnswerCorrectness,
            "AnswerRelevancy": AnswerRelevancy,
            "Faithfulness": Faithfulness,
            "ContextRecall": ContextRecall,
            "ContextPrecision": ContextPrecision,
            "RunConfig": RunConfig,
        }
    except ImportError as exc:
        raise ImportError(
            "RAGAS dependencies not installed. "
            "Run: pip install ragas langchain langchain-community langchain-ollama"
        ) from exc


def _import_langchain(
    judge_model: str,
    embed_model: str,
    ollama_base_url: str,
    timeout: int = 300,
):
    """Build LangChain-wrapped Ollama chat LLM and embedding model.

    Uses ``ChatOllama`` (chat model), NOT ``OllamaLLM`` (completion model).
    Official ragas (explodinggradients 0.1.x) sends every metric evaluation
    as a chat message (system + user roles).  A completion model receives only
    the raw concatenated text and cannot correctly handle those role boundaries,
    causing metrics to fail silently or return 0.  ChatOllama preserves the
    chat structure and is the supported interface for ragas + Ollama.
    """
    try:
        from langchain_ollama import ChatOllama, OllamaEmbeddings
        llm = ChatOllama(model=judge_model, base_url=ollama_base_url, timeout=timeout)
        embeddings = OllamaEmbeddings(model=embed_model, base_url=ollama_base_url)
        return llm, embeddings
    except ImportError:
        pass

    # Fallback to langchain-community
    try:
        from langchain_community.chat_models import ChatOllama
        from langchain_community.embeddings import OllamaEmbeddings
        llm = ChatOllama(model=judge_model, base_url=ollama_base_url, timeout=timeout)
        embeddings = OllamaEmbeddings(model=embed_model, base_url=ollama_base_url)
        return llm, embeddings
    except ImportError as exc:
        raise ImportError(
            "Neither langchain-ollama nor langchain-community is installed. "
            "Run: pip install langchain-ollama"
        ) from exc


# ---------------------------------------------------------------------------
# Metrics configuration per pipeline
# ---------------------------------------------------------------------------

# context_precision requires the judge to output a clean Yes/No per chunk.
# qwen2.5:7b (the default) is concise enough for this.  The larger 14b variant
# appends verbose reasoning that breaks the RAGAS parser, scoring all chunks 0.
_PIPELINE_METRICS: dict[str, list[str]] = {
    "rag_only": [
        "answer_correctness",
        "answer_relevancy",
        "faithfulness",
        "context_precision",
        "context_recall",
    ],
    "hybrid_rag": [
        "answer_correctness",
        "answer_relevancy",
        "faithfulness",
        "context_precision",
        "context_recall",
    ],
    "pretrained_only": [
        "answer_correctness",
        "answer_relevancy",
    ],
    "direct_kb": [
        "answer_correctness",
        "answer_relevancy",
        "faithfulness",
        "context_precision",
        "context_recall",
    ],
}

_ALL_KNOWN_PIPELINES = set(_PIPELINE_METRICS)


# ---------------------------------------------------------------------------
# JSONL loading helpers
# ---------------------------------------------------------------------------

def _load_jsonl(path: Path) -> list[dict]:
    records: list[dict] = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def _discover_jsonl_by_pipeline(
    run_dir: Path,
    pipeline_filter: set[str] | None,
    model_filter: set[str] | None,
) -> dict[str, list[dict]]:
    """Return {pipeline_name: [records, ...]} grouped by pipeline.

    Multiple JSONL files for the same pipeline (different models) are merged —
    this lets us evaluate all questions regardless of which model produced them.
    When a question appears in multiple files for the same pipeline, the first
    occurrence wins (same order as run_baseline output).
    """
    by_pipeline: dict[str, list[dict]] = {}

    for jsonl_path in sorted(run_dir.glob("*.jsonl")):
        records = _load_jsonl(jsonl_path)
        if not records:
            continue
        pipeline = records[0].get("pipeline", "")
        model = records[0].get("model", "")
        if pipeline_filter and pipeline not in pipeline_filter:
            continue
        if model_filter and model not in model_filter:
            continue

        if pipeline not in by_pipeline:
            by_pipeline[pipeline] = []
        # Deduplicate by question — keep first seen
        existing_questions = {r["question"] for r in by_pipeline[pipeline]}
        for rec in records:
            if rec["question"] not in existing_questions:
                by_pipeline[pipeline].append(rec)
                existing_questions.add(rec["question"])

    return by_pipeline


# ---------------------------------------------------------------------------
# RAGAS dataset builders
# ---------------------------------------------------------------------------

def _build_ragas_dataset(records: list[dict], pipeline: str, ragas_ns: dict):
    """Convert JSONL records to a ragas ``Dataset``."""
    Dataset = ragas_ns["Dataset"]

    questions: list[str] = []
    answers: list[str] = []
    ground_truths: list[str] = []
    contexts_list: list[list[str]] = []

    for rec in records:
        questions.append(rec["question"])
        answers.append(rec.get("answer") or "")
        ground_truths.append(rec.get("ground_truth") or "")

        raw_ctx = rec.get("contexts") or []
        if pipeline == "pretrained_only" or not raw_ctx:
            # RAGAS requires at least one non-empty string per row
            contexts_list.append([""])
        else:
            contexts_list.append([str(c) for c in raw_ctx if c])

    # Official ragas (explodinggradients) 0.1.x standard column names.
    data = {
        "question": questions,
        "answer": answers,
        "ground_truth": ground_truths,
        "contexts": contexts_list,
    }
    return Dataset.from_dict(data)


def _build_metrics(metric_names: list[str], ragas_ns: dict) -> list:
    """Instantiate RAGAS metric objects without LLM.

    In official ragas (explodinggradients) 0.1.x, the LLM and embeddings are
    injected globally by passing ``llm=`` and ``embeddings=`` to ``evaluate()``.
    Metric constructors do not accept LLM arguments — the LLM is set on the
    metric objects internally by evaluate() before scoring begins.
    """
    metric_map = {
        "answer_correctness": ragas_ns["AnswerCorrectness"],
        "answer_relevancy": ragas_ns["AnswerRelevancy"],
        "faithfulness": ragas_ns["Faithfulness"],
        "context_recall": ragas_ns["ContextRecall"],
        "context_precision": ragas_ns["ContextPrecision"],
    }
    return [metric_map[name]() for name in metric_names]


# ---------------------------------------------------------------------------
# Aggregate statistics
# ---------------------------------------------------------------------------

def _aggregate(values: list[float]) -> dict[str, float]:
    if not values:
        return {"mean": None, "std": None, "min": None, "max": None, "n": 0}
    return {
        "mean": round(statistics.mean(values), 4),
        "std": round(statistics.stdev(values), 4) if len(values) > 1 else 0.0,
        "min": round(min(values), 4),
        "max": round(max(values), 4),
        "n": len(values),
    }


# ---------------------------------------------------------------------------
# Main evaluation loop
# ---------------------------------------------------------------------------

def evaluate_pipeline(
    pipeline: str,
    records: list[dict],
    ragas_ns: dict,
    ragas_llm,
    ragas_embed,
    judge_timeout: int = 300,
) -> dict:
    """Evaluate one pipeline and return per-question + aggregate scores."""
    print(f"  Evaluating pipeline '{pipeline}' ({len(records)} questions) ...")
    metric_names = _PIPELINE_METRICS.get(pipeline, ["answer_correctness", "answer_relevancy"])

    dataset = _build_ragas_dataset(records, pipeline, ragas_ns)
    metrics = _build_metrics(metric_names, ragas_ns)

    # max_workers=1 prevents concurrent Ollama calls which cause resource
    # contention and make timeouts more likely on local hardware.
    run_config = ragas_ns["RunConfig"](
        timeout=judge_timeout,
        max_retries=1,
        max_workers=1,
    )

    # Official ragas 0.1.x: LLM and embeddings are injected at evaluate() level,
    # not on individual metric objects.
    evaluate_fn = ragas_ns["evaluate"]
    result = evaluate_fn(
        dataset=dataset,
        metrics=metrics,
        llm=ragas_llm,
        embeddings=ragas_embed,
        run_config=run_config,
    )

    # Convert to pandas then to list-of-dicts for JSON serialisation
    result_df = result.to_pandas()

    per_question: list[dict] = []
    for idx, row in result_df.iterrows():
        question_id = records[idx].get("question_id", idx + 1) if idx < len(records) else idx + 1
        entry: dict = {"question_id": question_id, "question": records[idx]["question"]}
        for name in metric_names:
            val = row.get(name)
            entry[name] = round(float(val), 4) if val is not None and val == val else None
        per_question.append(entry)

    aggregate: dict[str, dict] = {}
    for name in metric_names:
        values = [e[name] for e in per_question if e.get(name) is not None]
        aggregate[name] = _aggregate(values)

    return {"per_question": per_question, "aggregate": aggregate}


# ---------------------------------------------------------------------------
# Subprocess isolation (RAGAS 0.4.x closes asyncio loop after evaluate())
# ---------------------------------------------------------------------------

def _evaluate_pipeline_worker(
    pipeline: str,
    records: list[dict],
    judge_model: str,
    embed_model: str,
    ollama_base_url: str,
    judge_timeout: int,
    result_file: str,
) -> None:
    """Subprocess entry point. Writes a JSON result to result_file.

    Each pipeline must run in its own subprocess because RAGAS 0.4.x closes
    the asyncio event loop when evaluate() returns, making subsequent in-process
    calls to evaluate() fail with 'Event loop is closed'.  A fresh subprocess
    gets a new event loop automatically.
    """
    try:
        ragas_ns = _import_ragas()
        raw_llm, raw_embed = _import_langchain(
            judge_model=judge_model,
            embed_model=embed_model,
            ollama_base_url=ollama_base_url,
            timeout=judge_timeout,
        )
        ragas_llm = ragas_ns["LangchainLLMWrapper"](raw_llm)
        ragas_embed = ragas_ns["LangchainEmbeddingsWrapper"](raw_embed)
        result = evaluate_pipeline(
            pipeline=pipeline,
            records=records,
            ragas_ns=ragas_ns,
            ragas_llm=ragas_llm,
            ragas_embed=ragas_embed,
            judge_timeout=judge_timeout,
        )
        Path(result_file).write_text(
            json.dumps({"ok": True, "result": result}), encoding="utf-8"
        )
    except Exception as exc:
        Path(result_file).write_text(
            json.dumps({"ok": False, "error": str(exc), "tb": _traceback.format_exc()}),
            encoding="utf-8",
        )


def _run_pipeline_in_subprocess(
    pipeline_name: str,
    records: list[dict],
    judge_model: str,
    embed_model: str,
    ollama_url: str,
    judge_timeout: int,
) -> dict:
    """Spawn a fresh process for one pipeline, return its result dict."""
    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tf:
        result_file = tf.name

    ctx = multiprocessing.get_context("spawn")
    p = ctx.Process(
        target=_evaluate_pipeline_worker,
        args=(
            pipeline_name, records, judge_model, embed_model,
            ollama_url, judge_timeout, result_file,
        ),
    )
    p.start()
    # Outer timeout: give the subprocess 2× the per-call judge timeout to
    # account for multiple questions × multiple metrics per pipeline.
    p.join(timeout=judge_timeout * len(records) + 120)
    if p.is_alive():
        p.terminate()
        p.join()
        return {"error": f"Subprocess for '{pipeline_name}' timed out"}

    result_path = Path(result_file)
    if not result_path.exists() or result_path.stat().st_size == 0:
        return {"error": f"Subprocess for '{pipeline_name}' produced no output (exit code {p.exitcode})"}

    payload = json.loads(result_path.read_text(encoding="utf-8"))
    result_path.unlink(missing_ok=True)

    if payload.get("ok"):
        return payload["result"]
    return {"error": payload.get("error", "unknown subprocess error")}


def main() -> int:
    args = _parse_args()
    run_dir = Path(args.run_dir).resolve()
    if not run_dir.exists():
        raise FileNotFoundError(f"Run directory not found: {run_dir}")

    pipeline_filter = set(args.pipelines) if args.pipelines else None
    model_filter = set(args.models) if args.models else None

    by_pipeline = _discover_jsonl_by_pipeline(run_dir, pipeline_filter, model_filter)
    if not by_pipeline:
        print("No matching JSONL files found after filtering.")
        return 1

    print(f"Pipelines to evaluate: {', '.join(sorted(by_pipeline))}")
    print(f"Judge LLM     : {args.judge_model}")
    print(f"Embed model   : {args.embed_model}")
    print(f"Ollama URL    : {args.ollama_url}")

    # Evaluate — each pipeline runs in its own subprocess to get a fresh
    # asyncio event loop (RAGAS 0.4.x closes the loop after evaluate() returns,
    # which would break subsequent in-process evaluate() calls).
    results_by_pipeline: dict[str, dict] = {}
    for pipeline_name in sorted(by_pipeline):
        records = by_pipeline[pipeline_name]
        print(f"\nSpawning subprocess for pipeline '{pipeline_name}' ...")
        result = _run_pipeline_in_subprocess(
            pipeline_name=pipeline_name,
            records=records,
            judge_model=args.judge_model,
            embed_model=args.embed_model,
            ollama_url=args.ollama_url,
            judge_timeout=args.judge_timeout,
        )
        if "error" in result:
            print(f"  ERROR in '{pipeline_name}': {result['error']}")
        results_by_pipeline[pipeline_name] = result

    # Write output
    output_path = (
        Path(args.output).resolve()
        if args.output
        else run_dir / "ragas_scores.json"
    )
    output_data = {
        "metadata": {
            "run_dir": str(run_dir),
            "judge_model": args.judge_model,
            "embed_model": args.embed_model,
            "ollama_url": args.ollama_url,
            "run_date": datetime.now(tz=timezone.utc).isoformat(),
        },
        "by_pipeline": results_by_pipeline,
    }
    output_path.write_text(
        json.dumps(output_data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"\nRAGAS scores saved to: {output_path}")

    # Print a quick summary table
    _print_summary(results_by_pipeline)
    return 0


def _print_summary(results_by_pipeline: dict[str, dict]) -> None:
    """Print a compact per-pipeline aggregate summary to stdout."""
    print("\n" + "=" * 72)
    print("RAGAS Summary (means)")
    print("=" * 72)
    for pipeline, results in sorted(results_by_pipeline.items()):
        if "error" in results:
            print(f"  {pipeline}: ERROR — {results['error']}")
            continue
        agg = results.get("aggregate", {})
        row_parts = [f"{pipeline}:"]
        for metric, stats in agg.items():
            mean_val = stats.get("mean")
            row_parts.append(f"{metric}={mean_val:.3f}" if mean_val is not None else f"{metric}=n/a")
        print("  " + "  ".join(row_parts))
    print("=" * 72)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate a baseline JSONL run folder with RAGAS "
            "using an Ollama LLM as the judge."
        )
    )
    parser.add_argument(
        "--run-dir",
        required=True,
        help="Path to the timestamped baseline run folder (contains *.jsonl files).",
    )
    parser.add_argument(
        "--judge-model",
        default="qwen2.5:7b",
        help="Ollama model to use as the RAGAS judge LLM (default: qwen2.5:7b).",
    )
    parser.add_argument(
        "--embed-model",
        default="nomic-embed-text",
        help="Ollama embedding model for answer_relevancy (default: nomic-embed-text).",
    )
    parser.add_argument(
        "--ollama-url",
        default="http://localhost:11434",
        help="Ollama base URL (default: http://localhost:11434).",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output JSON path. Defaults to <run-dir>/ragas_scores.json.",
    )
    parser.add_argument(
        "--pipelines",
        nargs="+",
        default=None,
        metavar="PIPELINE",
        help="Evaluate only these pipelines (e.g. rag_only hybrid_rag).",
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=None,
        metavar="MODEL",
        help="Use only JSONL files from these models (e.g. gemma3:27b).",
    )
    parser.add_argument(
        "--judge-timeout",
        type=int,
        default=300,
        help=(
            "Timeout in seconds per judge LLM call (default: 300). "
            "Increase to 600 for large judge models like qwen2.5:7b on slow hardware."
        ),
    )
    return parser.parse_args()


if __name__ == "__main__":
    raise SystemExit(main())
